language: minimal
dist: xenial

addons:
  apt:
    packages:
      - lua-check

before_script:
  - pip install -r requirements.txt

script:
  - cd Addon && luacheck . -q && cd ..
  - cd Script && python3 -m unittest discover -s test && cd ..